# Generated by Django 5.2.1 on 2025-05-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareApp', '0004_doctor_alter_userprofile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.FileField(null=True, upload_to='doctor/'),
        ),
    ]
