# Generated by Django 5.2.1 on 2025-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareApp', '0004_doctoravailability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctoravailability',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays (Mon–Fri)')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='repeat_days',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
