# Generated by Django 5.2.1 on 2025-06-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareApp', '0005_rename_date_doctoravailability_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoravailability',
            name='repeat',
            field=models.CharField(choices=[('none', 'No Repeat'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('weekdays', 'Weekdays (Mon-Fri)')], default='none', max_length=20),
        ),
    ]
