# Generated by Django 5.2.1 on 2025-06-12 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicareApp', '0006_alter_doctoravailability_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctoravailability',
            name='repeat',
        ),
    ]
