# Generated by Django 5.2.1 on 2025-05-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicareApp', '0006_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('na', 'Not Prefer to Say')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
